/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciopropuesto85;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author USER
 */
public class VentanaHabitaciones extends javax.swing.JFrame {
    private Hotel hotel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaHabitaciones.class.getName());

    /**
     * Creates new form VentanaHabitaciones
     */
    public VentanaHabitaciones(Hotel hotel) {
            initComponents();        
            this.hotel = hotel;       
            setTitle("Habitaciones");
            setLocationRelativeTo(null);
            setResizable(false);
            inicio();                 
        
        habitaciónSeleccionada.setBounds(250, 180, 135, 23);
        campoHabitaciónSeleccionada = new JSpinner();
        SpinnerNumberModel modeloSpinner = new SpinnerNumberModel();
        modeloSpinner.setMinimum(1);
        modeloSpinner.setMaximum(10);
        modeloSpinner.setValue(1);
        campoHabitaciónSeleccionada.setModel(modeloSpinner);
    }
    
    private VentanaHabitaciones() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
private void inicio() {
        Habitación habitación;
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(0);
        if (!habitación.getDisponible()) { 
                disponibleHab1.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(1);
        if (!habitación.getDisponible()) {
                disponibleHab2.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(2);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(3);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(4);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(5);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(6);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(7);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(8);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        habitación = (Habitación) hotel.listaHabitaciones.elementAt(9);
        if (!habitación.getDisponible()) {
                disponibleHab3.setText("No disponible");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        habitación1 = new javax.swing.JLabel();
        disponibleHab1 = new javax.swing.JLabel();
        habitación2 = new javax.swing.JLabel();
        disponibleHab2 = new javax.swing.JLabel();
        habitación3 = new javax.swing.JLabel();
        habitación4 = new javax.swing.JLabel();
        habitación5 = new javax.swing.JLabel();
        disponibleHab3 = new javax.swing.JLabel();
        disponibleHab4 = new javax.swing.JLabel();
        disponibleHab5 = new javax.swing.JLabel();
        habitación6 = new javax.swing.JLabel();
        habitación7 = new javax.swing.JLabel();
        habitación8 = new javax.swing.JLabel();
        habitación9 = new javax.swing.JLabel();
        habitación10 = new javax.swing.JLabel();
        disponibleHab6 = new javax.swing.JLabel();
        disponibleHab7 = new javax.swing.JLabel();
        disponibleHab8 = new javax.swing.JLabel();
        disponibleHab9 = new javax.swing.JLabel();
        disponibleHab10 = new javax.swing.JLabel();
        habitaciónSeleccionada = new javax.swing.JLabel();
        campoHabitaciónSeleccionada = new javax.swing.JSpinner();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        habitación1.setText("Habitación 1");

        disponibleHab1.setText("Disponible");

        habitación2.setText("Habitación 2");

        disponibleHab2.setText("Disponible");

        habitación3.setText("Habitación 3");

        habitación4.setText("Habitación 4");

        habitación5.setText("Habitación 5");

        disponibleHab3.setText("Disponible");

        disponibleHab4.setText("Disponible");

        disponibleHab5.setText("Disponible");

        habitación6.setText("Habitación 6");

        habitación7.setText("Habitación 7");

        habitación8.setText("Habitación 8");

        habitación9.setText("Habitación 9");

        habitación10.setText("Habitación 10");

        disponibleHab6.setText("Disponible");

        disponibleHab7.setText("Disponible");

        disponibleHab8.setText("Disponible ");

        disponibleHab9.setText("Disponible");

        disponibleHab10.setText("Disponible");

        habitaciónSeleccionada.setText("Habitación a reservar:");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitación1)
                    .addComponent(habitación6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibleHab1)
                            .addComponent(disponibleHab6))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitación2)
                    .addComponent(habitación7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibleHab2)
                            .addComponent(disponibleHab7))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitación3)
                    .addComponent(habitación8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibleHab3)
                            .addComponent(disponibleHab8))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitación4)
                    .addComponent(habitación9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibleHab4)
                            .addComponent(disponibleHab9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitación5)
                    .addComponent(habitación10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disponibleHab5)
                            .addComponent(disponibleHab10))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(habitaciónSeleccionada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoHabitaciónSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitación1)
                    .addComponent(habitación2)
                    .addComponent(habitación3)
                    .addComponent(habitación4)
                    .addComponent(habitación5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disponibleHab1)
                    .addComponent(disponibleHab2)
                    .addComponent(disponibleHab3)
                    .addComponent(disponibleHab4)
                    .addComponent(disponibleHab5))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitación6)
                    .addComponent(habitación7)
                    .addComponent(habitación8)
                    .addComponent(habitación9)
                    .addComponent(habitación10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disponibleHab6)
                    .addComponent(disponibleHab7)
                    .addComponent(disponibleHab8)
                    .addComponent(disponibleHab9)
                    .addComponent(disponibleHab10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitaciónSeleccionada)
                    .addComponent(campoHabitaciónSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        int habitación = (int) campoHabitaciónSeleccionada.getValue();
        if (!hotel.buscarHabitaciónOcupada(habitación)) {
            VentanaIngreso ventanaIngreso = new
            VentanaIngreso(hotel, habitación);
            setVisible(false);
            ventanaIngreso.setVisible(true);
            } else 
        {
JOptionPane.showMessageDialog(this,"La habitación está ocupada","Mensaje",JOptionPane.INFORMATION_MESSAGE,null);
}
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaHabitaciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JSpinner campoHabitaciónSeleccionada;
    private javax.swing.JLabel disponibleHab1;
    private javax.swing.JLabel disponibleHab10;
    private javax.swing.JLabel disponibleHab2;
    private javax.swing.JLabel disponibleHab3;
    private javax.swing.JLabel disponibleHab4;
    private javax.swing.JLabel disponibleHab5;
    private javax.swing.JLabel disponibleHab6;
    private javax.swing.JLabel disponibleHab7;
    private javax.swing.JLabel disponibleHab8;
    private javax.swing.JLabel disponibleHab9;
    private javax.swing.JLabel habitación1;
    private javax.swing.JLabel habitación10;
    private javax.swing.JLabel habitación2;
    private javax.swing.JLabel habitación3;
    private javax.swing.JLabel habitación4;
    private javax.swing.JLabel habitación5;
    private javax.swing.JLabel habitación6;
    private javax.swing.JLabel habitación7;
    private javax.swing.JLabel habitación8;
    private javax.swing.JLabel habitación9;
    private javax.swing.JLabel habitaciónSeleccionada;
    // End of variables declaration//GEN-END:variables

}
