/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciopropuesto85;

import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class VentanaIngreso extends javax.swing.JFrame {
        private int númeroHabitaciónReservada; 
        private Hotel hotel;
        private Date fechaInicial; 
        private Habitación habitaciónReservada;
    

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngreso.class.getName());
   
    /**
     * Creates new form VentanaIngreso
     */
    public VentanaIngreso(Hotel hotel, int númeroHabitaciónReservada){
        initComponents();
        this.hotel = hotel;
        this.númeroHabitaciónReservada = númeroHabitaciónReservada;
        setTitle("Ingreso"); 
        setSize(380,300);
        setLocationRelativeTo(null);
        setResizable(false);
        
        habitación.setText("Habitación: " + númeroHabitaciónReservada);

   
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        campoFechaIngreso.setText(sdf.format(new java.util.Date()));
    
    }

    private VentanaIngreso() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoFechaIngreso = new javax.swing.JTextField();
        habitación = new javax.swing.JLabel();
        fechaIngreso = new javax.swing.JLabel();
        huésped = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        documentoIdentidad = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoDocumentoIdentidad = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaIngresoActionPerformed(evt);
            }
        });

        habitación.setText("Habitación: 1");

        fechaIngreso.setText("Fecha (aaaa-mm-dd)");

        huésped.setText("Huésped");

        nombre.setText("Nombre");

        apellidos.setText("Apellidos");

        documentoIdentidad.setText("Doc. identidad");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(huésped)
                    .addComponent(habitación)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aceptar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fechaIngreso)
                                .addComponent(nombre)
                                .addComponent(apellidos)
                                .addComponent(documentoIdentidad)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombre)
                                    .addComponent(campoFechaIngreso)
                                    .addComponent(campoApellidos)
                                    .addComponent(campoDocumentoIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelar)
                                .addGap(43, 43, 43)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(habitación)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaIngreso)
                    .addComponent(campoFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(huésped)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentoIdentidad)
                    .addComponent(campoDocumentoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaIngresoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
    int posición = -1;
    for (int i = 0; i < hotel.listaHabitaciones.size(); i++) {
            Habitación habitación = (Habitación) hotel.listaHabitaciones.elementAt(i);
        if (habitación.getNúmeroHabitación() == this.númeroHabitaciónReservada) {

            try {
            posición = i;
            String fechaIngresada = campoFechaIngreso.getText();
            SimpleDateFormat formatoFecha = new
            SimpleDateFormat("yyyy-MM-dd");
            Date fecha = formatoFecha.parse(fechaIngresada);
            Huésped huésped = new Huésped(nombre.getText(), apellidos.getText(),
            Integer.parseInt(campoDocumentoIdentidad.getText()));
            huésped.setFechaIngreso(fecha); 
            habitación.setHuésped(huésped); 
            habitación.setDisponible(false);
            habitaciónReservada = habitación;
            hotel.listaHabitaciones.set(posición, habitación);
            
        JOptionPane.showMessageDialog(this,"El huésped ha sido registrado","Mensaje", JOptionPane.INFORMATION_MESSAGE,null);
        setVisible(false);
        break;
} 
catch (ParseException e) { 
         JOptionPane.showMessageDialog(this,"La fecha no está en el formato solicitado", "Mensaje",JOptionPane.ERROR_MESSAGE);
} 
catch (Exception e) { 
        JOptionPane.showMessageDialog(this,"Campo nulo o error en formato de numero","Error", JOptionPane.ERROR_MESSAGE);
}
        }   
    }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        setVisible(false);
        campoFechaIngreso.setText("");
        campoNombre.setText("");
        campoApellidos.setText("");
        campoDocumentoIdentidad.setText("");
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaIngreso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel apellidos;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDocumentoIdentidad;
    private javax.swing.JTextField campoFechaIngreso;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel documentoIdentidad;
    private javax.swing.JLabel fechaIngreso;
    private javax.swing.JLabel habitación;
    private javax.swing.JLabel huésped;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables

 
}
