/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciopropuesto85;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VentanaSalida extends javax.swing.JFrame {
    private Hotel hotel; 
    private int númeroHabitación; 
    private int posiciónHabitación; 
    private Habitación habitaciónOcupada;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaSalida.class.getName());

    /**
     * Creates new form VentanaSalida
     */
    public VentanaSalida(Hotel hotel, int número) {
        initComponents();  
        this.hotel = hotel;
        this.númeroHabitación = número;
        setTitle("Salida huéspedes"); 
        setSize(300,330);
        setLocationRelativeTo(null);
        setResizable(false);
}

    private VentanaSalida() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void inicio() {
        String fecha = hotel.buscarFechaIngresoHabitación(númeroHabitación);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        habitación = new javax.swing.JLabel();
        fechaIngreso = new javax.swing.JLabel();
        fechaSalida = new javax.swing.JLabel();
        campoFechaSalida = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        cantidadDías = new javax.swing.JLabel();
        totalPago = new javax.swing.JLabel();
        registrarSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        habitación.setText("Habitación: 1");

        fechaIngreso.setText("Fecha de ingreso:");

        fechaSalida.setText("Fecha de salida (aaaa-mm-dd):");

        campoFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaSalidaActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        cantidadDías.setText("Cantidad de días:");

        totalPago.setText("Total: $");

        registrarSalida.setText("Registrar Salida");
        registrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(habitación))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantidadDías)
                            .addComponent(fechaSalida)
                            .addComponent(fechaIngreso)
                            .addComponent(campoFechaSalida)
                            .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalPago)
                            .addComponent(registrarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(habitación)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaSalida)
                .addGap(18, 18, 18)
                .addComponent(campoFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidadDías)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarSalida)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarSalidaActionPerformed
        habitaciónOcupada.setHuésped(null); 
        habitaciónOcupada.setDisponible(true); 
        hotel.listaHabitaciones.set(posiciónHabitación,habitaciónOcupada);
        JOptionPane.showMessageDialog(this,"Se ha registrado la salida del huésped","Mensaje", JOptionPane.INFORMATION_MESSAGE,null);
        setVisible(false); 
    }//GEN-LAST:event_registrarSalidaActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        String fechaS = campoFechaSalida.getText();
        String fechaI = hotel.buscarFechaIngresoHabitación(númeroHabitación);
        for (int i = 0; i < hotel.listaHabitaciones.size(); i++) { 
            habitaciónOcupada = (Habitación) hotel.listaHabitaciones.elementAt(i);
        if (habitaciónOcupada.getNúmeroHabitación() == this.númeroHabitación) {
            try {
                posiciónHabitación = i;
                SimpleDateFormat formatoFecha = new
                SimpleDateFormat("yyyy-MM-dd");
                Date fecha2 = formatoFecha.parse(fechaS);
                habitaciónOcupada.getHuésped().setFechaSalida(fecha2);
                Date fecha1 = habitaciónOcupada.getHuésped().getFechaIngreso();
                if (fecha1.compareTo(fecha2) < 0) {
                int cantidad = habitaciónOcupada.getHuésped().obtenerDíasAlojamiento();
                cantidadDías.setText("Cantidad de días: " + cantidad);
                double valor = cantidad * habitaciónOcupada.getPrecioDía();
                totalPago.setText("Total: $" + valor);
                registrarSalida.setEnabled(true); 
                } else {
                JOptionPane.showMessageDialog(this,"La fecha de salida es menor que la de ingreso","Mensaje", JOptionPane.ERROR_MESSAGE);
                }
                } catch (ParseException e) {
                JOptionPane.showMessageDialog(this,"La fecha no está en el formato solicitado","Mensaje",JOptionPane.ERROR_MESSAGE);
                }
                }
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void campoFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaSalida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField campoFechaSalida;
    private javax.swing.JLabel cantidadDías;
    private javax.swing.JLabel fechaIngreso;
    private javax.swing.JLabel fechaSalida;
    private javax.swing.JLabel habitación;
    private javax.swing.JButton registrarSalida;
    private javax.swing.JLabel totalPago;
    // End of variables declaration//GEN-END:variables
}
